TARGET = micro_speech

NUCLEI_SDK_ROOT = ../../../..

SRCDIRS = . src micro_features testdata

INCDIRS = . inc micro_features testdata

MIDDLEWARE := tflm

NMSIS_LIB := nmsis_nn nmsis_dsp

COMMON_FLAGS := -O2

include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
