TARGET = micro_speech

NUCLEI_SDK_ROOT = ../../../..

SRCDIRS = . models testdata

INCDIRS = . mdoels testdata

MIDDLEWARE := tflm

NMSIS_LIB := nmsis_nn

COMMON_FLAGS := -O2

include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
