TARGET = hello_world

NUCLEI_SDK_ROOT = ../../../..

SRCDIRS = . models

INCDIRS = . models

MIDDLEWARE := tflm

NMSIS_LIB := nmsis_nn nmsis_dsp

COMMON_FLAGS := -O2

include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
