TARGET = person_detection

NUCLEI_SDK_ROOT = ../../../..

SRCDIRS = . src

INCDIRS = . inc

MIDDLEWARE := tflm

NMSIS_LIB := nmsis_nn nmsis_dsp

COMMON_FLAGS := -O2

include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
